eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8772

spring:
  application:
    name: zipkin-user-service
  zipkin:
    base-url: http://127.0.0.1:8771
  sleuth:
    sampler:
      percentage: 1.0