
server:
  port: 8766

spring:
  application:
    name: micro-service-05-zuul-router
##(Zipkin 链路跟踪 start)
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:8771
##(Zipkin 链路跟踪 end)

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: micro-service-04-ribbon
    api-b:
      path: /api-b/**
      serviceId: micro-service-05-forein
    api-c:
      path: /zipkin-c/**
      serviceId: zipkin-user-service